- hosts: localhost
  name: Install Service Mesh Demo
  vars:
    insecure_skip_tls_verify: true
    operators_project: openshift-operators
    minio_stateful: false
    threescale_project: demo-3scale
    rhsso_project: demo-rhsso
    ossm_project: istio-system
    sm_instance_name: basic
  tasks:

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443')   }}"

    - name: login as super user with token on OpenShift 4
      command: "oc login --token={{ token }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - token is not none
       - token|trim() != ""
      ignore_errors: no

    # - name: Service Mesh Role
    #   include_role:
    #     name: service-mesh

    - name: Install 3scale
      include_role:
        name: 3scale

    # - name: Install RHSSO
    #   include_role:
    #     name: rhsso

    # - name: Install Bookinfo
    #   include_role:
    #     name: bookinfo
